name: Deploy to GoDaddy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the static site
        run: npm run build

      - name: Debug and Clean Remote Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "--- Contents of target directory before cleaning ---"
            ls -la ${{ secrets.TARGET_DIR }}
            echo "--- Cleaning target directory ---"
            find ${{ secrets.TARGET_DIR }} -mindepth 1 -delete
            echo "--- Contents of target directory after cleaning ---"
            ls -la ${{ secrets.TARGET_DIR }}

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "out/"
          target: ${{ secrets.TARGET_DIR }}
          strip_components: 1 